TIME_VERY_SHORT = "TIME_VERY_SHORT"
TIME_SHORT = "TIME_SHORT"
TIME_MEDIUM = "TIME_MEDIUM"
TIME_LONG = "TIME_LONG"
NUMBER_LARGE = "NUMBER_LARGE"
NUMBER_MEDIUM = "NUMBER_MEDIUM"
NUMBER_FEW = "NUMBER_FEW"
NUMBER_VERY_FEW = "NUMBER_VERY_FEW"
DIFFICULTY_HARD = "DIFFICULTY_HARD"
DIFFICULTY_MEDIUM = "DIFFICULTY_MEDIUM"
DIFFICULTY_EASY = "DIFFICULTY_EASY"
DIFFICULTY_VERY_EASY = "DIFFICULTY_VERY_EASY"
DECISION_TABLE = {
    TIME_LONG: [
        [DIFFICULTY_HARD, NUMBER_LARGE],
        [DIFFICULTY_HARD, NUMBER_MEDIUM],
        [DIFFICULTY_MEDIUM, NUMBER_LARGE]
    ],
    TIME_MEDIUM: [
        [DIFFICULTY_HARD, NUMBER_FEW],
        [DIFFICULTY_HARD, NUMBER_VERY_FEW],
        [DIFFICULTY_MEDIUM, NUMBER_MEDIUM],
        [DIFFICULTY_MEDIUM, NUMBER_FEW],
        [DIFFICULTY_EASY, NUMBER_LARGE],
        [DIFFICULTY_EASY, NUMBER_MEDIUM],
        [DIFFICULTY_VERY_EASY, NUMBER_LARGE]
    ],
    TIME_SHORT: [
        [DIFFICULTY_MEDIUM, NUMBER_VERY_FEW],
        [DIFFICULTY_EASY, NUMBER_FEW],
        [DIFFICULTY_EASY, NUMBER_VERY_FEW],
        [DIFFICULTY_VERY_EASY, NUMBER_MEDIUM],
        [DIFFICULTY_VERY_EASY, NUMBER_FEW]
    ],
    TIME_VERY_SHORT: [
        [DIFFICULTY_VERY_EASY, NUMBER_VERY_FEW]
    ]
}
